### ISSUE TITLE
Trying to set the delay lower than 1ms will crash OBS

### ISSUE THREAD

**Issue by thelegendtubaguy** [exeldro/obs-recursion-effect#2]
I realize I did a stupid thing, but I don't think this should result in an OBS crash.  I was using move-transition to add/subtract 100ms from the delay.  I hit the button one too many times, I think it tried to subtract 100ms from 75ms resulting in OBS crashing.

Crash report here:
https://obsproject.com/logs/3CyukEQRgLbp3X4L

**Comment by exeldro** [comment]
This build should fix it:
https://github.com/exeldro/obs-recursion-effect/actions/runs/3639586475

**Comment by thelegendtubaguy** [comment]
That fixed it.  It will now only go down to 1ms.
