### ISSUE TITLE
System Memory isn't Freed on Effect/Source Disable. VRAM is Never Freed until Destroy

### ISSUE THREAD

**Issue by NarryG** [exeldro/obs-recursion-effect#3]
When the filter is disabled (source disabled, filter disabled, scene swap), memory is not instantly freed. 

System memory is slowly freed until the buffer is eventually empty. This is a partial leak if a user is unaware that the memory usage persists until the buffer eventually empties 

Additionally, VRAM appears to be fully leaking and is not freed until the filter or source is destroyed. 

Video showing this here. This is an extreme example for demonstration purposes.
https://user-images.githubusercontent.com/3047793/228428309-07a50aba-820a-4baf-a8cc-16870d4a8022.mp4

The memory usage persists across scene swaps. That means that if you use the filter anywhere, such as in an intro or a BRB screen, then swap sources, the VRAM is never freed, starving OBS and other applications of memory. While the system memory frees, this appears to move at the rate of filter update.

A potential option for "Clear buffer on disable" could address the use-case of a user who doesn't care about the history once the source is disabled.

OBS Version: 29.0.2.

**Comment by NarryG** [comment]
Looking at the source code, it appears that there's supposed to be a "Reset Trigger" combobox that can be selected in the filter UI that'd address this, but that reset trigger combobox doesn't appear.

**Comment by NarryG** [comment]
It appears I had an outdated version as the version hosted on Github is outdated. 
Using the latest build from the OBS website, if I set the ResetTrigger to hide, the memory is cleared.


It might be worth removing the "0.0.1 release" that's listed here on GitHub if newer builds aren't posted.

**Comment by exeldro** [comment]
created a 0.0.5 release on GitHub
